### ISSUE TITLE
A line that does not end with `;` causes some issues:

### ISSUE THREAD

**Issue by stefanpenner** [SparshithNR/doc-tester#3]
A small modification to the example in the readme reveals new lines are ignored:

```js
import {
  subtract
} from './add';
const numbers = {
  a: 4,
  b: 3
};
console.log('hello')
subtract(numbers.a, numbers.b) // equals: 1;
add( {
  a: 4
}.a, 4) // equals: 8;
```

Specifically I added a `console.log(` without a trailing `;` (which is valid JS)

Result:

```js
node ./bin/doc-test -f ./README.md                                                                                        (127)
Not all tests passed:
SyntaxError: unknown: Unexpected token, expected "," (12:59)

  10 | assert.notEqual(add(4, 5), 6);
  11 | assert.throws(() => { throw add(2, 3) }, 'Throws error');
> 12 | const numbers = {  a: 4,  b: 3};assert.equal(console.log(1)subtract(numbers.a, numbers.b), 1);
     |                                                            ^
  13 | assert.equal(add( {  a: 4}.a, 4), 8);
  14 | ;assert.expect(5);
  15 |     });
```

**Comment by stefanpenner** [comment]
if I replace the `console.log` with `debugger` we survive babel, but crash during test running:

```
 node ./bin/doc-test -f ./README.md                                                                                  (1) (735ms)
Not all tests passed:
Error: Command failed: node node_modules/.bin/qunit test.js

TAP version 13
not ok 1 Test the doc > samples
  ---
  message: "Died on test #4     at Object.<anonymous> (/Users/spenner/src/SparshithNR/markdown-test/test.js:8:3): debuggersubtract is not defined"
  severity: failed
  actual: null
  expected: undefined
  stack: ReferenceError: debuggersubtract is not defined
    at Object.<anonymous> (/Users/spenner/src/SparshithNR/markdown-test/test.js:18:12)
  ...
1..1
# pass 0
# skip 0
# todo 0
# fail 1
```

**Comment by SparshithNR** [comment]
Done with #10

**Comment by SparshithNR** [comment]
@mike-north I need assertion to be terminated with `;`. I use this as a delimiter while parsing.

**Comment by mike-north** [comment]
> @mike-north I need assertion to be terminated with `;`. I use this as a delimiter while parsing.

Hmm... is there a reason you're not just using a newline? Seems like the semicolon is extra noise

**Comment by SparshithNR** [comment]
Reason for that is developer can have more comments following `;`.  Our interest will confine from `//` to `;`

**Comment by mike-north** [comment]
Let's look at this together. At the very least, the semicolon should be optional, only to be used in the event that I wish to add more info after the assertion

**Comment by stefanpenner** [comment]
@SparshithNR that is true, but I think we can accomplish both. @mike-north is right, that the extra noise is unfortunate.

I think the following lines could be all made valid

* `1+1 // equals: 2`
* `1+1 // equals: 2;`
* `1+1 // equals: 2; <some comment>`

```
const REGEXP = /(.*)\/\/\s*(\w+-?\w+?)(?::\s*([^;]+))?(?:;(.*))?/
const assert = require("assert");

[line, expression, assertion, expected] = '1+1//equals:2'.match(REGEXP)
assert.equal(expression, '1+1');
assert.equal(assertion, 'equals');
assert.equal(expected, '2');

[line, expression, assertion, expected] = '1+1 // equals: 2'.match(REGEXP)
assert.equal(expression, '1+1 ');
assert.equal(assertion, 'equals');
assert.equal(expected, '2');

[line, expression, assertion, expected] = '1+1 // equals: 2;'.match(REGEXP)
assert.equal(expression, '1+1 ');
assert.equal(assertion, 'equals');
assert.equal(expected, '2');

[line, expression, assertion, expected, comment] = '1+1 // equals: 2; SOME COMMENT'.match(REGEXP)
assert.equal(expression, '1+1 ');
assert.equal(assertion, 'equals');
assert.equal(expected, '2');
assert.equal(comment, ' SOME COMMENT');
```

**Comment by stefanpenner** [comment]
note is there a reason this project doesn't use named capture blocks in the regular expressions? I think they could make it more readable, but I left it out in-case we can't use them do to node-support issues.

**Comment by stefanpenner** [comment]
with named expressions:

```js
const REGEXP = /(?<expression>.*)\/\/\s*(?<assertion>\w+-?\w+?)(?::\s*(?<expected>[^;]+))?(?:;(?<comment>.*))?/
const assert = require("assert");

{
  let { groups: { expression, assertion, expected, comment } } = '1+1//equals:2'.match(REGEXP)
  assert.equal(expression, '1+1');
  assert.equal(assertion, 'equals');
  assert.equal(expected, '2');
  assert.equal(comment, undefined);
}
{
  let { groups: { expression, assertion, expected, comment } } = '1+1 // equals: 2'.match(REGEXP)
  assert.equal(expression, '1+1 ');
  assert.equal(assertion, 'equals');
  assert.equal(expected, '2');
}
{
  let { groups: { expression, assertion, expected, comment } } = '1+1 // equals: 2;'.match(REGEXP)
  assert.equal(expression, '1+1 ');
  assert.equal(assertion, 'equals');
  assert.equal(expected, '2');
}
{
  let { groups: { expression, assertion, expected, comment } } = '1+1 // equals: 2; SOME COMMENT'.match(REGEXP)
  assert.equal(expression, '1+1 ');
  assert.equal(assertion, 'equals');
  assert.equal(expected, '2');
  assert.equal(comment, ' SOME COMMENT');
}
```

**Comment by stefanpenner** [comment]
man I wish JavaScript had inline comments in RegExp's

**Comment by stefanpenner** [comment]
Looks like there are plans to add free-spacing and comments: https://tc39.github.io/tc39-notes/2015-11_nov-17.html#regexp-buffet

**Comment by SparshithNR** [comment]
I tried named block, it is supported only after node 10. If we want to support node 8, we need can not use named capture blocks.

**Comment by SparshithNR** [comment]
The REGEX above is a non-greedy so stops while processing the `not-equal` assertion [regEx101](https://regex101.com/r/F0SCty/1/). We can fix this in couple of ways.

- Change `not-equal` to `notEqual`.
- make regex greedy. Ex: add `\n` at the end of regex. 
```js
const REGEXP = /(.*)\/\/\s*(\w+-?\w+?)(?::\s*([^;]+))?(?:;(.*))?\n/;
```

**Comment by stefanpenner** [comment]
I don’t think this has to do with greediness. Rather the \w doesn’t include -

So instead replace \w with [a-z\-] and then make the regexp case insensitive but adding i to the end

**Comment by SparshithNR** [comment]
This will fail for cases `foo(a) // no asseting comment`
https://regex101.com/r/F0SCty/1/
